# Generated by Django 5.0.6 on 2024-06-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreeJuniorapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='Prenom',
        ),
    ]
