# Generated by Django 5.0.6 on 2024-06-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeJuniorapp1', '0003_program_school_specialty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdescription',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentphoto',
            name='student',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='student_cvs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='student_photos/'),
        ),
        migrations.DeleteModel(
            name='StudentCV',
        ),
        migrations.DeleteModel(
            name='StudentDescription',
        ),
        migrations.DeleteModel(
            name='StudentPhoto',
        ),
    ]
