# Generated by Django 5.0.6 on 2024-06-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeJuniorapp1', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Company_name',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('moderated', 'Moderated')], default='visible', max_length=20),
        ),
    ]
