# Generated by Django 5.0.6 on 2024-06-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeJuniorapp1', '0008_student_is_active_student_is_staff'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='student_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='student_set', to='auth.permission'),
        ),
    ]
