# Generated by Django 5.0.6 on 2024-06-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeJuniorapp1', '0009_student_groups_student_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_level',
            field=models.CharField(choices=[('Bac+3', 'Bac+3'), ('Bac+4', 'Bac+4'), ('Bac+5', 'Bac+5'), ('Bac+6', 'Bac+6'), ('Bac+7', 'Bac+7')], max_length=5, null=True),
        ),
    ]
