# Generated by Django 5.0.6 on 2024-06-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeJuniorapp1', '0010_alter_student_study_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
