# Generated by Django 5.0.6 on 2024-06-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeJuniorapp1', '0012_remove_student_description_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
